### ISSUE TITLE
Question: How does the extension track time? 

### ISSUE THREAD

**Issue by kherel** [twentyTwo/vsc-ext-coding-time-tracker#2]
Hello,

I have a question about how the extension tracks time:

Does it track time based on user activity, such as typing or interacting with VS Code?
If I stop typing and switch to another window (e.g., to watch YouTube) without closing VS Code, will it stop the timer?
Thank you for clarifying this!

**Comment by twentyTwo** [comment]
Hi @kherel ,
The system tracks time only while the text editor is in focus. If you stop typing or switch to another window, the editor loses focus, and time tracking pauses.

Additionally, the tracked time is saved every minute. For instance, if you switch away from the editor at the 30-second mark, those 30 seconds won’t be counted. When you return and refocus on the editor, the timer restarts from zero.
